/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSubmit: typeof import('./src/components/global/form/ButtonSubmit.vue')['default']
    Checkbox: typeof import('./src/components/global/form/Checkbox.vue')['default']
    DatePicker: typeof import('./src/components/global/form/DatePicker.vue')['default']
    Dropdown: typeof import('./src/components/global/form/Dropdown.vue')['default']
    ErrorMessage: typeof import('./src/components/global/form/ErrorMessage.vue')['default']
    InputEmail: typeof import('./src/components/global/form/InputEmail.vue')['default']
    InputPassword: typeof import('./src/components/global/form/InputPassword.vue')['default']
    InputText: typeof import('./src/components/global/form/InputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
